// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getDatabaseUrl(): string {
  const {
    POSTGRES_USER,
    POSTGRES_PASSWORD,
    POSTGRES_HOST,
    POSTGRES_DB,
    POSTGRES_PORT,
    POSTGRES_SCHEMA = "public",
  } = process.env;

  if (!POSTGRES_USER || !POSTGRES_PASSWORD || !POSTGRES_HOST || !POSTGRES_DB)
    throw new Error("Missing required PostgreSQL environment variables");

  const encodedPassword = encodeURIComponent(POSTGRES_PASSWORD);

  let url = `postgresql://${POSTGRES_USER}:${encodedPassword}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}`;

  const params = new URLSearchParams();
  if (POSTGRES_SCHEMA) params.append("schema", POSTGRES_SCHEMA);

  const query = params.toString();
  if (query) url += `?${query}`;

  return url;
}

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
