const OTP_MAX_ATTEMPTS = 3;
const OTP_COOLDOWN_SECONDS = 60;
const OTP_EXPIRES_MINUTES = 10 * 60 * 1000;

const RESET_AFTER_HOURS = 1;

export {
  OTP_MAX_ATTEMPTS,
  OTP_COOLDOWN_SECONDS,
  OTP_EXPIRES_MINUTES,
  RESET_AFTER_HOURS,
};
